name: hlcm_li

model_type: segmented_discretechoice

probability_mode: single_chooser

choice_mode: aggregate

remove_alts: True

prediction_sample_size: null

segmentation_col: income_quartile

choosers_fit_filters: null

choosers_predict_filters:
  - income < 24000

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

default_config:
    model_expression: np.log1p(residential_price) + sum_residential_units + ave_income
        +  autoPeakTotal - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.03172683451212808
                ave_income: -0.4808734060559246
                np.log1p(residential_price): -0.3187340340756076
                sum_residential_units: 0.5737292436764879
            Std. Error:
                autoPeakTotal: 0.012657310742085114
                ave_income: 0.011506345242403598
                np.log1p(residential_price): 0.021517707082255807
                sum_residential_units: 0.009563841895734795
            T-Score:
                autoPeakTotal: -2.5066015331864664
                ave_income: -41.7920196139946
                np.log1p(residential_price): -14.8126393233806
                sum_residential_units: 59.98941115205543
        fitted: true
        log_likelihoods:
            convergence: -65664.09232682174
            'null': -68690.71849420968
            ratio: 0.04406164666399681
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.03462001203730808
                ave_income: -0.34042982330463095
                np.log1p(residential_price): -0.07466351930242808
                sum_residential_units: 0.37924072884537574
            Std. Error:
                autoPeakTotal: 0.013210084171794657
                ave_income: 0.011632189773303528
                np.log1p(residential_price): 0.02194214233290554
                sum_residential_units: 0.009720813484447538
            T-Score:
                autoPeakTotal: -2.620726074647318
                ave_income: -29.2661854680135
                np.log1p(residential_price): -3.4027451909496964
                sum_residential_units: 39.01327079797675
        fitted: true
        log_likelihoods:
            convergence: -67365.07990241774
            'null': -68709.13917495361
            ratio: 0.019561579269877116
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.05242066954548329
                ave_income: 0.029616837778679767
                np.log1p(residential_price): -0.014507449861351055
                sum_residential_units: 0.20167752480311513
            Std. Error:
                autoPeakTotal: 0.013861405402813528
                ave_income: 0.011965389363557458
                np.log1p(residential_price): 0.022694791253598155
                sum_residential_units: 0.00977074089225903
            T-Score:
                autoPeakTotal: 3.7817716185433237
                ave_income: 2.475208861057432
                np.log1p(residential_price): -0.6392413880013532
                sum_residential_units: 20.640965411629757
        fitted: true
        log_likelihoods:
            convergence: -68279.33292683754
            'null': -68718.34951532558
            ratio: 0.006388636973740591
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.0039409609269164605
                ave_income: 1.2792993302680151
                np.log1p(residential_price): -0.01
                sum_residential_units: 0.19705090067327294
            Std. Error:
                autoPeakTotal: 0.014826185523650401
                ave_income: 0.012571372922172658
                np.log1p(residential_price): 0.022107266480099176
                sum_residential_units: 0.009312120026421752
            T-Score:
                autoPeakTotal: 0.265810846669221
                ave_income: 101.7628971941212
                np.log1p(residential_price): 13.066396081045502
                sum_residential_units: 21.16069167001396
        fitted: true
        log_likelihoods:
            convergence: -66932.73716533386
            'null': -68769.0063873714
            ratio: 0.02670198856289918
        name: 4

fitted: true
